Repository 9ivot/triplus, pull requests merged in 2022-12, with the labels that each got.

#8 docs: branch 전략 & 피그마 링크 추가
  README.md
  README.old.md
Labels: documentation

#10 feat: deletealert 추가
  src/components/DeleteAlert/index.jsx
  src/pages/Home/index.jsx
Labels: HTML, CSS

#11 feat: Navbar 컴포넌트 생성
  src/components/Navbar/Navbar.jsx
  src/pages/Home/index.jsx
Labels: HTML, CSS

#13 feat: UserInfo component html,css 추가
  src/components/Header/SearchButton.jsx
  src/components/Header/SearchInput.jsx
  src/components/Header/Vertical.jsx
  src/components/Header/index.jsx
  src/components/Header/style.js
  src/components/MainContainer.js
  src/components/Navbar/Navbar.jsx
  src/components/UserInfo/index.jsx
  src/pages/Home/index.jsx
Labels: HTML, CSS

#14 style: 로고 & 유저 이미지등 이미지 업로드
  src/assets/images/error_404.png
  src/assets/images/plain_blue.png
  src/assets/images/plain_gray.png
  src/assets/images/plain_white.png
  src/assets/images/triplus.png
  src/assets/images/user_img_big.png
  src/assets/images/user_img_small.png
Labels: image

#15 feat: PostCard 컴포넌트 완성
  src/components/MainContainer.js
  src/components/PostCard/PostCardBtns.jsx
  src/components/PostCard/index.jsx
  src/components/UserInfo/index.jsx
  src/index.jsx
  src/pages/Home/index.jsx
Labels: HTML, CSS

#20 Feat: deletealert 코드수정
  src/components/DeleteAlert/index.jsx
  src/pages/Home/index.jsx
Labels: HTML, CSS

#23 feat: ProductUpload 페이지 html, css 완성 & 이미지 추가
  src/App.jsx
  src/assets/images/file_gray.png
  src/assets/images/save_button.png
  src/pages/ProductUpload/index.jsx
Labels: HTML, CSS, image

#24 Feat/profile
  src/App.jsx
  src/components/MainContainer.js
  src/components/PostCard/PostCardBtns.jsx
  src/components/PostCard/index.jsx
  src/components/UserInfo/index.jsx
  src/components/UserInfomation/index.jsx
  src/pages/MyProfile/BottomSection.jsx
  src/pages/MyProfile/MidSection.jsx
  src/pages/MyProfile/TopSection.jsx
  src/pages/MyProfile/TopSectionMy.jsx
  src/pages/MyProfile/TopSectionYour.jsx
  src/pages/MyProfile/index.jsx
  src/theme.js
Labels: HTML, CSS

#27 style: textarea 높이값 조정
  src/components/PostCard/index.jsx
  src/pages/PostUpload/index.jsx
Labels: enhancement

#28 Feat/follow
  src/App.jsx
  src/components/UserInfo/index.jsx
  src/pages/Follow/index.jsx
  src/pages/Followers/index.jsx
  src/pages/Profile/BottomSection.jsx
  src/pages/Profile/MidSection.jsx
  src/pages/Profile/TopSection.jsx
  src/pages/Profile/TopSectionMy.jsx
  src/pages/Profile/TopSectionYour.jsx
  src/pages/Profile/index.jsx
  src/theme.js
Labels: HTML, CSS

#31 feat: Home페이지 팔로우한 유저 업을시 보여주는ui 완성
  src/App.jsx
  src/components/MainContainer.js
  src/pages/ErrorPage/index.jsx
  src/pages/Home/HomeNoFollow.jsx
  src/pages/Home/index.jsx
  src/pages/PostUpload/index.jsx
Labels: HTML, CSS

#29 feat: PostModal 컴포넌트 완성
  src/components/DeleteAlert/index.jsx
  src/components/PostModal/index.jsx
  src/pages/PostUpload/index.jsx
Labels: HTML, CSS

#32 feat: search 페이지 html,css 완성 router url 재설정
  src/App.jsx
  src/components/Header/Prev.jsx
  src/components/Header/SearchButton.jsx
  src/pages/ErrorPage/index.jsx
  src/pages/Home/HomeNoFollow.jsx
  src/pages/Search/index.jsx
Labels: HTML, CSS

#34 feat: ChatRoom 페이지 html, css 완성
  src/App.jsx
  src/pages/ChatRoom/ChatBar.jsx
  src/pages/ChatRoom/ChatHeader.jsx
  src/pages/ChatRoom/ChatReceive.jsx
  src/pages/ChatRoom/ChatSend.jsx
  src/pages/ChatRoom/Chattings.jsx
  src/pages/ChatRoom/index.jsx
Labels: HTML, CSS

#36 style: navbar EditIcon을 UploadIcon으로 변경
  src/App.jsx
  src/components/Navbar/index.jsx
Labels: HTML, CSS

#37 feat: SplashScreenUI 구현
  package-lock.json
  package.json
  src/assets/images/plain_blue.png
  src/assets/images/triplus.png
  src/pages/SplashScreen/index.jsx
  src/pages/SplashScreen/splashEvent.jsx
Labels: HTML, CSS

#38 build: axios 설치
  package-lock.json
  package.json
Labels: module

#39 style: SNSLogin -> MultiLogin으로 명칭 변경
  src/App.jsx
  src/pages/MultiLogin/index.jsx
  src/pages/SNSLogin/index.jsx
Labels: directory

#40 style:plane-white 이미지 변경
  src/assets/images/plain_white.png
Labels: image

#43 feat: 프로필 페이지 유저 정보 가져온 후 ui에 표시
  src/components/Header/Vertical.jsx
  src/components/PostCard/index.jsx
  src/pages/Profile/TopSection.jsx
  src/pages/Profile/TopSectionYour.jsx
  src/pages/Profile/index.jsx
Labels: JavaScript

#46 feat: 프로필 페이지 프로필 데이터 가져오기
  src/App.jsx
  src/components/PostCard/PostCardBtns.jsx
  src/components/PostCard/index.jsx
  src/pages/Profile/BottomSection.jsx
  src/pages/Profile/MidSection.jsx
  src/pages/Profile/TopSection.jsx
  src/pages/Profile/index.jsx
Labels: JavaScript

#47 feat: 업로드 버튼 클릭 시 게시글 POST
  src/assets/images/more_vertical.png
  src/assets/images/upload_button.png
  src/assets/images/upload_file.png
  src/pages/PostDetail/Comment.jsx
  src/pages/PostUpload/index.jsx
  src/pages/PostUpload/style.js
Labels: JavaScript, HTML, CSS, image

#50 feat: MultiLogin page UI 구현
  src/pages/MultiLogin/JoinLink.jsx
  src/pages/MultiLogin/LoginModal.jsx
  src/pages/MultiLogin/SocialLoginItem.jsx
  src/pages/MultiLogin/index.jsx
Labels: HTML, CSS

#51 feat: route 설정
  src/App.jsx
  src/pages/EmailLogin/index.jsx
  잠깐.txt
Labels: documentation, JavaScript

#52 style: Login 제거
  src/pages/EmailLogin/index.jsx
Labels: JavaScript

#53 style: Login 컴포넌트 제거
  src/pages/EmailLogin/index.jsx
Labels: JavaScript

#55 feat: 이미지 프리뷰 생성 및 삭제 기능 구현
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/components/CommentBar/index.jsx
  src/pages/PostUpload/PreviewList.jsx
  src/pages/PostUpload/index.jsx
  src/pages/PostUpload/style.js
Labels: JavaScript, HTML, CSS, image

#57 feat: 팔로우 페이지 팔로우기능, 언팔로우기능 추가
  src/components/UserInfo/index.jsx
  src/pages/Follow/IsFollowButton.jsx
  src/pages/Follow/index.jsx
  src/pages/Profile/BottomSection.jsx
  src/pages/Profile/MidSection.jsx
  src/pages/Profile/TopSection.jsx
  src/pages/Profile/TopSectionMy.jsx
Labels: JavaScript, CSS

#59 style: route 변경 & 일부 추가
  src/App.jsx
Labels: JavaScript

#60 feat: 검색페이지 다른 유저 검색 기능
  src/App.jsx
  src/assets/images/user_img_big.png
  src/assets/images/user_img_small.png
  src/components/Header/SearchInput.jsx
  src/components/UserInfo/index.jsx
  src/pages/Profile/MidSection.jsx
  src/pages/Profile/TopSection.jsx
  src/pages/Search/index.jsx
Labels: JavaScript

#61 feat: 프로필 페이지 url 변경
  src/App.jsx
  src/components/Navbar/index.jsx
Labels: JavaScript

#62 Feat/heart
  src/components/PostCard/PostCardBtns.jsx
  src/components/UserInfo/index.jsx
  src/pages/Follow/IsFollowButton.jsx
  src/pages/Follow/index.jsx
  src/pages/Profile/BottomSection.jsx
  src/pages/Profile/MidSection.jsx
  src/pages/Profile/TopSection.jsx
  src/pages/Profile/TopSectionYour.jsx
  src/pages/Search/index.jsx
Labels: JavaScript

#63 Refactor: 레티나 디스플레이 대응하기 위해 이미지 png -> svg로 변경
  src/assets/images/circle.png
  src/assets/images/circle.svg
  src/assets/images/error_404.png
  src/assets/images/error_404.svg
  src/assets/images/file_gray.png
  src/assets/images/file_gray.svg
  src/assets/images/plain_blue.png
  src/assets/images/plain_blue.svg
  src/assets/images/plain_gray.png
  src/assets/images/plain_white.png
  src/assets/images/plain_white.svg
  src/assets/images/upload_file.png
  src/assets/images/upload_file.svg
  src/assets/images/user_img_big.png
  src/assets/images/user_img_big.svg
  src/assets/images/user_img_small.png
  src/assets/images/user_img_small.svg
  src/components/CommentBar/index.jsx
  src/components/PostCard/index.jsx
  src/components/UserInfo/index.jsx
  src/pages/ChatList/ChattingList.jsx
  src/pages/ChatRoom/ChatBar.jsx
  src/pages/ErrorPage/index.jsx
  src/pages/Home/HomeNoFollow.jsx
  src/pages/MultiLogin/index.jsx
  src/pages/PostUpload/style.js
  src/pages/ProductUpload/index.jsx
  src/pages/Profile/TopSection.jsx
  src/pages/SplashScreen/index.jsx
Labels: directory

#64 feat: 홈페이지에서 팔로워 게시글 피드 불러오기
  src/pages/Home/index.jsx
Labels: JavaScript

#65 feat: ProductUpload 페이지 이미지 업로드 기능 추가, 버튼 이미지 삭제
  src/assets/images/save_button.png
  src/pages/ProductUpload/index.jsx
Labels: JavaScript, CSS, image

#66 feat: PostDetail 페이지 댓글 기능 추가
  src/App.jsx
  src/components/CommentBar/index.jsx
  src/pages/PostDetail/Comment.jsx
  src/pages/PostDetail/UserPostDetail.jsx
  src/pages/PostDetail/index.jsx
  src/pages/PostDetail/style.js
  src/pages/PostUpload/index.jsx
Labels: JavaScript, HTML, CSS

#67 feat: 게시글 삭제/수정, 신고. 로그아웃/개인정보설정 모달창 ui
  src/components/DeleteAlert/index.jsx
  src/components/Header/Vertical.jsx
  src/components/Modal/AlertModal.jsx
  src/components/Modal/ModalContainer.jsx
  src/components/Modal/ModalList.jsx
  src/components/PostCard/index.jsx
  src/components/PostModal/index.jsx
  src/pages/Home/index.jsx
Labels: JavaScript

#68 feat: 댓글 신고/삭제 모달 추가
  src/components/PostCard/index.jsx
  src/pages/PostDetail/Comment.jsx
Labels: JavaScript

#69 feat: 게시글 신고 기능 추가
  src/components/PostCard/index.jsx
  src/pages/Home/index.jsx
  src/pages/ProductUpload/index.jsx
Labels: JavaScript

#70 refactor: 팔로우 리스트 불러오는 기능 커스텀 hook으로 관리
  src/hooks/useGetFollowList.js
  src/pages/Follow/index.jsx
Labels: JavaScript

#71 feat: (임시) 로그인 결과값객체를 로컬스트리지에 삽입하는 기능 구현
  src/pages/EmailLogin/index.jsx
  src/pages/EmailSignUp/index.jsx
Labels: JavaScript, HTML, CSS

#72 feat: ProductUpload 페이지 상품등록 유효성 검사
  src/pages/ProductUpload/index.jsx
Labels: JavaScript

#75 refactor: 댓글, 게시글, 프리뷰 가져오는 커스텀 훅 완성
  src/hooks/useGetCommentList.js
  src/hooks/useGetPostData.js
  src/hooks/useGetPreview.js
  src/pages/PostDetail/Comment.jsx
  src/pages/PostDetail/index.jsx
  src/pages/PostUpload/index.jsx
Labels: JavaScript

#76 refactor: 모달창, 좋아요 기능 커스텀 훅으로 관리, 팔로우 기능 utils에 저장
  src/components/Header/Vertical.jsx
  src/components/Modal/ModalContainer.jsx
  src/components/PostCard/PostCardBtns.jsx
  src/components/PostCard/index.jsx
  src/hooks/useGetFollowList.js
  src/hooks/useHeartBtn.js
  src/hooks/useModal.js
  src/pages/Follow/IsFollowButton.jsx
  src/pages/Follow/index.jsx
  src/pages/Home/index.jsx
  src/pages/Profile/BottomSection.jsx
  src/pages/Profile/MidSection.jsx
  src/pages/Profile/TopSection.jsx
  src/pages/Profile/TopSectionYour.jsx
  src/pages/Search/index.jsx
  src/utils/handleFollow.js
Labels: JavaScript

#77 refactor: axios.get 데이터 불러오는 api 커스텀 훅으로 관리
  src/hooks/useGetData.js
  src/pages/Follow/index.jsx
  src/pages/Home/index.jsx
  src/pages/Profile/BottomSection.jsx
  src/pages/Profile/MidSection.jsx
  src/pages/Profile/TopSection.jsx
Labels: JavaScript

#78 feat: Long size button 컴포넌트 구현
  src/components/Button/LongBtn.jsx
Labels: JavaScript, HTML, CSS

#79 feat: 회원가입 페이지 InputBox 컴포넌트 구현
  src/components/Button/LongBtn.jsx
  src/components/InputBox/index.jsx
Labels: JavaScript, HTML, CSS

#80 refactor: 피그마 디자인에 맞춰 place holder 간격 변경
  src/components/InputBox/index.jsx
Labels: CSS

#81 feat: 게시물 수정 기능
  src/App.jsx
  src/components/PostCard/index.jsx
  src/hooks/useFollowBtn.js
  src/hooks/useGetFollowList.js
  src/hooks/usePostUpload.js
  src/pages/Follow/IsFollowButton.jsx
  src/pages/Follow/index.jsx
  src/pages/PostUpload/index.jsx
  src/pages/Profile/TopSection.jsx
  src/pages/Profile/TopSectionYour.jsx
Labels: JavaScript

#84 feat: 프로필 편집 이동시 location.state에 데이터 전달
  src/components/PostCard/index.jsx
  src/pages/Follow/index.jsx
  src/pages/Home/index.jsx
  src/pages/MyProfileEdit/index.jsx
  src/pages/PostUpload/index.jsx
  src/pages/Profile/BottomSection.jsx
  src/pages/Profile/TopSection.jsx
  src/pages/Profile/TopSectionMy.jsx
  src/pages/Search/index.jsx
  src/pages/SetProfile/index.jsx
Labels: JavaScript

#86 feat: ProductUpload 상품 등록 구현
  src/pages/ProductUpload/index.jsx
Labels: JavaScript

#87 refactor: 게시글/댓글 삭제 클릭 시 뜨는 alert창 제거
  src/pages/Profile/TopSectionMy.jsx
  src/utils/handleDelete.js
Labels: JavaScript

#88 feat: navbar 버튼 클릭 시 아이콘 및 텍스트 색상 변경
  src/components/Navbar/index.jsx
Labels: JavaScript, HTML, CSS

#90 feat: 홈 게시글 피드, 나의 게시글 목록 초기 10개의 게시글 가져온 후 스크롤 바닥으로 이동 시 추가로 데이터 가져온다
  src/hooks/useReloadData.js
  src/pages/Home/index.jsx
  src/pages/Profile/BottomSection.jsx
  src/pages/Profile/TopSectionYour.jsx
Labels: JavaScript

#91 feat: 채팅방 페이지 이미지 업로드 및 텍스트 입력 시 전송 버튼 활성화
  src/components/Button/SaveBtn/index.jsx
  src/components/Button/SaveBtn/style.js
  src/components/CommentBar/index.jsx
  src/components/Navbar/index.jsx
  src/pages/ChatRoom/ChatBar.jsx
  src/pages/ChatRoom/ChatHeader.jsx
  src/pages/ChatRoom/ChatReceive.jsx
  src/pages/ChatRoom/ChatSend.jsx
  src/pages/ChatRoom/ChatVertical.js
  src/pages/ChatRoom/Chattings.jsx
  src/pages/ChatRoom/style.js
  src/pages/PostDetail/UserPostDetail.jsx
  src/pages/PostDetail/index.jsx
  src/pages/PostDetail/style.js
  src/pages/PostUpload/index.jsx
  src/pages/PostUpload/style.js
Labels: JavaScript, HTML, CSS

#94 feat: 이메일로 회원가입 페이지 구현
  src/components/BaseURL/index.jsx
  src/components/InputBox/index.jsx
  src/pages/EmailSignUp/index.jsx
Labels: JavaScript, HTML, CSS

#95 feat: 게시글 업로드 페이지 여러 이미지 미리보기 구현
  src/components/CommentBar/index.jsx
  src/components/CommentBar/style.js
  src/pages/PostUpload/PreviewList.jsx
  src/pages/PostUpload/index.jsx
  src/pages/PostUpload/style.js
  src/utils/handleDeclaration.js
Labels: JavaScript, CSS

#96 feat: 게시글 두장이상 보여주기
  src/components/Button/FollowBtn/IsFollowButton.jsx
  src/components/Button/FollowBtn/style.js
  src/components/PostCard/index.jsx
  src/components/PostCard/style.js
  src/hooks/useReloadData.js
  src/pages/Follow/IsFollowButton.jsx
  src/pages/Follow/index.jsx
  src/pages/Home/index.jsx
  src/pages/Profile/TopSectionYour.jsx
Labels: JavaScript

#97 feat: 용량 큰 파일 업로드 가능
  src/pages/ProductUpload/index.jsx
  src/pages/ProductUpload/style.js
Labels: JavaScript

#98 feat: 게시글 수정 기능 구현
  src/components/CommentBar/index.jsx
  src/pages/PostUpload/index.jsx
  src/pages/PostUpload/style.js
Labels: JavaScript, CSS

#99 feat: 프로필 수정 화면 구현
  src/components/ImageBox/Index.jsx
  src/pages/EmailSignUp/index.jsx
  src/pages/MyProfileEdit/index.jsx
Labels: JavaScript, HTML, CSS

#100 feat: 나의 게시물 앨범형 추가
  src/components/ImageBox/Index.jsx
  src/pages/EmailSignUp/index.jsx
  src/pages/Home/index.jsx
  src/pages/MyProfileEdit/index.jsx
  src/pages/Profile/BottomSection.jsx
  src/pages/Profile/style.js
Labels: JavaScript

#101 feat: 로그인 화면 구현
  src/components/BaseURL/index.jsx
  src/components/Button/LongBtn.jsx
  src/components/ImageBox/Index.jsx
  src/pages/EmailLogin/index.jsx
  src/pages/EmailSignUp/index.jsx
  src/pages/MyProfileEdit/index.jsx
  src/theme.js
Labels: JavaScript, HTML, CSS, module, directory

#102 feat: 게시물 리로드 시 해당 데이터를 받을 때까지의 로딩 표시
  src/hooks/useReloadData.js
  src/pages/Home/index.jsx
  src/pages/Home/style.js
  src/pages/Profile/BottomSection.jsx
  src/pages/Profile/style.js
Labels: JavaScript

#103 fix: 게시물이 적을때 리로딩 텍스트 뜨는 버그 수정
  src/hooks/useReloadData.js
  src/pages/Home/index.jsx
  src/pages/Profile/BottomSection.jsx
Labels: JavaScript

#104 feat: 로딩페이지 완성
  src/App.jsx
  src/assets/images/loading.png
  src/pages/LoadingPage/index.jsx
  src/pages/LoadingPage/style.js
Labels: HTML, CSS, image

#105 style: 로딩 페이지 함수명 변경
  src/pages/LoadingPage/index.jsx
Labels: directory

#106 feat: 데이터 불러올때 대기 시간 로딩화면 보여주기
  src/hooks/useGetData.js
  src/hooks/useReloadData.js
  src/pages/Follow/index.jsx
  src/pages/Follow/style.js
  src/pages/Home/index.jsx
  src/pages/Profile/BottomSection.jsx
  src/pages/Profile/MidSection.jsx
  src/pages/Profile/TopSection.jsx
  src/pages/Profile/style.js
  src/pages/YourProfile/index.jsx
Labels: JavaScript

#107 fix: 나의 게시물 앨범형 loding 오타 수정
  src/pages/Profile/BottomSection.jsx
Labels: JavaScript

#108 feat: 게시글 업로드 / 상세 페이지 데이터 불러올 때 로딩페이지 나타나게 설정
  public/favicon.ico
  public/index.html
  src/components/Button/FollowBtn/IsFollowButton.jsx
  src/components/Navbar/index.jsx
  src/components/Navbar/style.js
  src/pages/ChatList/ChattingList.jsx
  src/pages/ChatList/index.jsx
  src/pages/ChatList/style.js
  src/pages/Home/index.jsx
  src/pages/PostDetail/index.jsx
  src/pages/PostUpload/index.jsx
  src/pages/ProductUpload/index.jsx
Labels: JavaScript, HTML, CSS, image

#109 style: styled components props로 theme color 내려주도록 변경, 회원가입 후 홈화면으로 이동하도록 경로변경
  src/components/Button/MiddleSmallBtn/MiddleSmallBtn.jsx
  src/components/Button/SaveBtn/style.js
  src/pages/MyProfileEdit/index.jsx
Labels: JavaScript, HTML, CSS

#110 feat: 프로필 수정 화면 UI 구현
  src/pages/SetProfile/index.jsx
Labels: JavaScript, HTML, CSS

#111 feat: 로그인 할때와 로그 아웃 했을때의 보여주는 페이지 ui
  src/App.jsx
  src/components/Header/Vertical.jsx
  src/pages/EmailLogin/index.jsx
  src/pages/MultiLogin/JoinLink.jsx
  src/pages/MultiLogin/index.jsx
  src/pages/Profile/BottomSection.jsx
  src/pages/Profile/TopSection.jsx
  src/pages/Profile/index.jsx
  src/pages/Profile/style.js
  src/pages/SplashScreen/index.jsx
Labels: JavaScript

#112 feat: 1차 배포 연습
  package-lock.json
  package.json
  src/index.jsx
  src/pages/SetProfile/index.jsx
Labels: JavaScript

#114 style: 회원 가입 후 로그인 화면으로 바로 이동하도록 설정
  src/pages/MyProfileEdit/index.jsx
Labels: JavaScript

#115 style: splash 화면 이후 로그인 화면 나오도록 순서 조정
  src/pages/MultiLogin/index.jsx
  src/pages/SplashScreen/index.jsx
Labels: JavaScript, HTML, CSS

#116 refacotr: 좋아요버튼 이미지 크기 차이 사이즈 조정, 메인 홈 헤더 로고 변경
  src/assets/images/main_logo.svg
  src/components/PostCard/style.js
  src/pages/Home/index.jsx
  src/pages/Home/style.js
  src/pages/Profile/TopSection.jsx
Labels: JavaScript

#117 feat: useGetData 결과값의 데이터 형 추가
  src/components/PostCard/index.jsx
  src/hooks/useGetData.js
  src/hooks/useObserver.js
  src/pages/Home/index.jsx
  src/pages/PostDetail/index.jsx
  src/pages/PostUpload/index.jsx
  src/pages/Profile/MidSection.jsx
  src/pages/Profile/TopSection.jsx
Labels: JavaScript

#118 style: 게시물 상세/업로드 페이지 유저 프로필 이미지 원형으로 변경
  src/components/CommentBar/index.jsx
  src/components/CommentBar/style.js
  src/components/Navbar/style.js
  src/pages/PostUpload/index.jsx
  src/pages/PostUpload/style.js
Labels: JavaScript, CSS

#120 build: gh-pages 설정 복구
  package.json
Labels: build

#121 build: gh-pages 설정 복구
  package.json
Labels: build

#122 fix: npm start입력시 페이지가 나타나지 않는 현상 수정
  src/index.jsx
Labels: bug

#123 feat: 프로필 페이지 앨범형 여러개 이미지 시 레이아웃 이미지 추가
  src/assets/images/icon_img_layers.svg
  src/assets/images/plain_gray.svg
  src/hooks/useFollowBtn.js
  src/hooks/useObserver.js
  src/pages/Home/HomeNoFollow.jsx
  src/pages/Home/index.jsx
  src/pages/Home/style.js
  src/pages/PostDetail/index.jsx
  src/pages/Profile/BottomSection.jsx
  src/pages/Profile/MidSection.jsx
  src/pages/Profile/TopSection.jsx
  src/pages/Profile/style.js
  src/pages/Search/index.jsx
Labels: JavaScript

#124 style: setprofile과 myprofileedit 교체
  src/App.jsx
  src/pages/EmailSignUp/index.jsx
  src/pages/MyProfileEdit/index.jsx
  src/pages/Profile/TopSectionMy.jsx
  src/pages/SetProfile/index.jsx
Labels: directory
