Repository 9ivot/triplus, pull requests merged in 2023-01, with the labels that each got.

#125 feat: 상품 클릭시 해당 url로 이동
  src/pages/Profile/MidSection.jsx
Labels: JavaScript

#127 feat: 게시글 상세페이지 댓글 무한스크롤 IntersectionObserver로 구현
  src/hooks/useCommentReloadGetData.js
  src/pages/PostDetail/index.jsx
  src/pages/PostDetail/style.js
Labels: bug, question, JavaScript

#128 feat: 옵저버 커스텀 훅 생성
  Read.md
  src/hooks/useObserver.js
  src/hooks/useReloadData.js
  src/pages/Follow/index.jsx
  src/pages/Home/index.jsx
  src/pages/PostDetail/index.jsx
  src/pages/Profile/BottomSection.jsx
Labels: JavaScript

#129 fix: 게시글 삭제 시 리로드해야하는 버그 수정
  src/components/CommentBar/index.jsx
  src/hooks/useObserver.js
  src/pages/PostDetail/index.jsx
  src/pages/Profile/BottomSection.jsx
Labels: JavaScript

#130 feat: 404페이지 연결
  src/App.jsx
  src/pages/ErrorPage/index.jsx
  src/pages/ErrorPage/style.js
Labels: JavaScript

#131 fix: 게시물 상세페이지에서 댓글 스크롤 다 내린 후 댓글 입력했을 때 상단에 안뜨는 오류 해결
  src/components/CommentBar/index.jsx
  src/pages/PostDetail/index.jsx
  src/pages/PostDetail/style.js
Labels: JavaScript

#132 feat: 프로필 수정 페이지 구현
  src/components/ImageBox/index.jsx
  src/pages/MyProfileEdit/index.jsx
  src/pages/SetProfile/index.jsx
Labels: bug, JavaScript, HTML, CSS

#133 fix: 게시글 댓글 삭제 시 스크롤 위로올라가는 버그 수정
  src/components/PostCard/index.jsx
  src/hooks/useObserver.js
  src/pages/PostDetail/Comment.jsx
  src/pages/PostDetail/index.jsx
  src/pages/PostDetail/style.js
  src/pages/Profile/BottomSection.jsx
  src/utils/handleDelete.js
Labels: JavaScript

#134 docs: Readme.md 수정 2차
  README.md
  src/pages/MyProfileEdit/index.jsx
Labels: documentation

#135 style: title 대소문자 변경
  public/index.html
Labels: HTML

#136 feat: index.js에 폰트 스타일 추가
  src/components/PostCard/index.jsx
  src/font.css
  src/index.jsx
Labels: CSS

#137 refactor: home 타이틀 이미지로 변경
  src/assets/images/main_home_logo.svg
  src/assets/images/main_logo.svg
  src/hooks/useCommentReloadGetData.js
  src/hooks/useObserver.js
  src/pages/Home/index.jsx
Labels: JavaScript

#138 fix: 이미지 정보를 받아올 수 없는 현상 해결
  src/components/ImageBox/index.jsx
  src/pages/SetProfile/index.jsx
Labels: bug, JavaScript

#139 build: gh-pages 설정
  package.json
  src/App.jsx
  src/index.jsx
  src/pages/Home/index.jsx
  src/pages/Profile/BottomSection.jsx
  src/pages/Search/index.jsx
Labels: JavaScript

#141 fix: 배포 후 옵저버 실행 안되는 버그 수정Feat/observer
  src/components/ImageBox/index.jsx
  src/hooks/useObserver.js
  src/index.jsx
  src/pages/MyProfileEdit/index.jsx
Labels: JavaScript

#142 docs: readme 수정 3차
  README.md
Labels: documentation

#143 docs: 리드미 수정 4차
  README.md
  src/hooks/useObserver.js
Labels: directory

#144 fix: error message 올바르게 수정
  src/components/ImageBox/index.jsx
  src/pages/EmailLogin/index.jsx
  src/pages/EmailSignUp/index.jsx
  src/pages/MyProfileEdit/index.jsx
  src/pages/SetProfile/index.jsx
Labels: JavaScript, HTML, CSS

#145 docs: 리드미 7차 수정
  README.md
Labels: documentation

#146 docs: 트러블 슈팅 2번 수정
  README.md
Labels: documentation

#147 docs: readme 8차 수정
  README.md
Labels: documentation

#148 feat: 게시물 여러개의 이미지일시 swiper 적용
  package-lock.json
  package.json
  src/components/Navbar/style.js
  src/components/PostCard/index.jsx
  src/components/PostCard/style.js
Labels: JavaScript

#149 feat: navbar z-index 수정
  Read.md
  src/components/Navbar/style.js
  src/components/PostCard/index.jsx
Labels: documentation, CSS

#150 style: css부분 style.js파일로 분리
  src/pages/EmailLogin/index.jsx
  src/pages/EmailLogin/style.js
  src/pages/EmailSignUp/index.jsx
  src/pages/EmailSignUp/style.js
  src/pages/MyProfileEdit/index.jsx
  src/pages/MyProfileEdit/style.js
  src/pages/SetProfile/index.jsx
  src/pages/SetProfile/style.js
Labels: CSS

#151 feat: 상품 삭제 기능 구현
  src/components/ProductCard/index.jsx
  src/components/ProductCard/style.js
  src/pages/Profile/MidSection.jsx
Labels: JavaScript

#152 feat: 게시글 위치 추가 기능
  .env
  package-lock.json
  package.json
  public/index.html
  src/assets/images/map_choose.svg
  src/assets/images/marker_icon.svg
  src/components/LocationInfo/index.jsx
  src/components/LocationInfo/style.js
  src/components/Map/MapModal.jsx
  src/components/Map/style.js
  src/components/PostCard/index.jsx
  src/components/PostCard/style.js
  src/hooks/usePostUpload.js
  src/pages/PostUpload/index.jsx
  src/pages/PostUpload/style.js
  src/pages/Profile/BottomSection.jsx
  src/pages/Profile/MidSection.jsx
Labels: JavaScript

#153 refactor: 게시글 및 상품 업로드 페이지 이미지 파일 압축
  package-lock.json
  package.json
  src/hooks/useGetPreview.js
  src/pages/PostUpload/index.jsx
  src/pages/ProductUpload/index.jsx
Labels: image

#154 docs: 리드미 서정연 느낀 점 수정
  README.md
Labels: documentation

#155 feat: 상품 수정 기능 구현
  src/App.jsx
  src/components/ProductCard/index.jsx
  src/hooks/useGetPreview.js
  src/pages/PostUpload/index.jsx
  src/pages/ProductUpload/index.jsx
Labels: JavaScript

#156 style: locationInfo에 margin-top추가
  src/components/LocationInfo/style.js
  src/components/Map/index.jsx
  src/pages/PostUpload/index.jsx
Labels: CSS

#157 fix: 지도 설정 하지 않은 후 게시글 등록시 글자 깨지는 현상 수정
  src/components/PostCard/index.jsx
Labels: JavaScript

#158 fix: 게시글 수정 시 글자 깨지는 현상 수정
  src/pages/PostUpload/index.jsx
Labels: bug

#159 refactor: 홈, 프로필, 검색, 팔로우의 데이터 변수명 변경
  src/pages/Follow/index.jsx
  src/pages/Home/index.jsx
  src/pages/Profile/BottomSection.jsx
  src/pages/Profile/MidSection.jsx
  src/pages/Profile/TopSection.jsx
  src/pages/Search/index.jsx
Labels: JavaScript
